image:
- Visual Studio 2017
- Ubuntu1804

install: 
  - pwsh: dotnet tool install --global git-flow-version
  - pwsh: dotnet tool install --global coverlet.console
  - pwsh: Get-ChildItem Env:

build_script:
  - pwsh: ./build.ps1
  