image:
- Visual Studio 2017
- Ubuntu1804

install: 
  - ps: dotnet tool install --global git-flow-version
  - ps: dotnet tool install --global coverlet.console

build_script:
  - ps: build.ps1
  
after_build:
  - ps: |
      Update-AppveyorBuild -Version $env:version