# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@1
  inputs:
    inlineScript: 'dotnet tool install --global coverlet.console'

- task: PowerShell@1
  inputs:
    inlineScript: 'dotnet tool install --global coverlet.console'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.1.0'
    checkLatest: true

- task: PowerShell@2
  inputs:
    filePath: 'build.ps1'

- task: GitTag@5
  inputs:
    workingdir: '$(SYSTEM.DEFAULTWORKINGDIRECTORY)'
    tag: '$(env:versionShort)'

- task: DocFxTask@0
  inputs:
    solution: './doc'